spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: food_ai
    password: a1234
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 50 # 서비스 상황에 맞게 모니터링 후 조정

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.OracleDialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: "food-ai-group"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  threads:
    virtual:
      enabled: true # 가상 스레드 활성화


server:
  port: 8082

  tomcat:
    max-connections: 12000 # 10,000명 접속 대비
    accept-count: 1000

#DB 환경 로그 확인
#logging:
#  level:
#    com.zaxxer.hikari: DEBUG

